
--delete from  MRG_MAREOGRAFI;
--delete from  MRG_BOE;
--delete from  MRG_TENDENZE;
--delete from  MRG_PROVENIENZE;
--delete from  MRG_TIPI_MACRO_AREE;
--delete from  MRG_TIPI_ALLEGATO;
--delete from  MRG_ESTENSIONI;
--delete from  MRG_STATI_RELAZIONI;
--delete from  MRG_LOCALITA;
--delete from MRG_TIPI_DANNO;
--delete from MRG_STB;